import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import styles from "/usr/src/app/pages/styles/home.module.css";
// import { Post } from "/usr/src/app/pages/api/types";
import Link from "next/link";

interface Post {
    id: string;
    title: string;
    content: string;
    created_at: string;
    updated_at: string;
}

type Props = {
    posts: Post[];
};

// ISRを適用
export async function getStaticProps(){
    const res = await fetch("http://localhost:3002/api/v1/posts");
    const posts = await res.json();

    console.log(posts); //debug

    return {
        props:{
            posts,
        },
        revalidate: 60 * 60 * 24, // 24時間ごとにISRが発火する
    };
}

// export default function Home({ posts }: Props) {
//     return (
//         <>
//             <head>
//                 <title>Create next app</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/usr/src/app/app/favicon.ico" />
//             </head>
            
            
//             <div>
//                 {posts.map((post) => (
//                     <div key={post.id} className={styles.postCard}>
//                         <Link href={`posts/${post.id}`} className={styles.postCardBox}>
//                             <h2>{post.title}</h2>
//                         </Link>
//                         <p>{post.content}</p>
//                         <button className={styles.editButton}>edit</button>
//                         <button className={styles.deleteButton}>delete</button>
//                     </div>
//                 ))}
//             </div>
//         </>
//     );
// }

export default function Home() {
  return (
    <head>
        <title>Create next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/usr/src/app/app/favicon.ico" />
    </head>
  )
}